### ISSUE TITLE
Put all test files into the test directory

### ISSUE THREAD

**Issue by nwin** [PistonDevelopers/image#160]
This makes it easier to exclude them for packaging.

**Comment by jeremija** [comment]
Hi, shouldn't unit tests, as well as documentation tests, be included in the module file itself, whereas the integration tests should go to the `tests` directory? I'm asking out of curiosity because that's what I read in the [Rust Book](https://doc.rust-lang.org/book/testing.html) and I kind of liked the idea of having unit tests right next to the actual code for brevity and clarity.

**Comment by nwin** [comment]
I was talking about the test images but this also happened already.
