### ISSUE TITLE
Deprecate `read_scanline`

### ISSUE THREAD

**Issue by nwin** [PistonDevelopers/image#183]
I would like to deprecate `ImageDecoder::read_scanline`. It is tricky to implement for animated and progressive images as well as images that are not ordered in scanlines. The decoder would have to hold an extra buffer internally.

Any objections?

**Comment by retep998** [comment]
I feel that this is a low level detail that most users should not be relying on anyway, so I'm in support of this.

**Comment by bvssvni** [comment]
+1

**Comment by jramapuram** [comment]
Would the alternative be storing the entire image buffer internally? My use case of `image` is to try to speed up image cropping of large images which generally don't fit in system memory. What would the alternative to `read_scanline` and `load_rect` be?

**Comment by HeroicKatora** [comment]
As far as I can tell, the interface is too general. It is not guaranteed that for any arbitrary encoding the functions `read_scanline` or `load_rect` result in speed or memory usage improvements compared to a full load and following crop, especially for formats which do not follow a pixel raster encoding of any sorts. At the same time, requiring them is a big burden for the implementation of a decoder. 

The alternative is implementing them on the specific encoders which can support them in a useful fashion but not in the generic interface. For the few decoders where this old interface is actually supported, that means simply moving the implementation from the trait to the struct itself.

**Comment by jramapuram** [comment]
@HeroicKatora  : thanks, I'm sure that would be fine. Just out of curiosity: what **are** the image formats that support `load_rect` efficiently ?

**Comment by pix64** [comment]
I imagine a read_chunk function would be easier to implement. It's not
guaranteed to be a single line. It could be a portion of a line, a whole
line, multiple lines, or the entire image.

**Comment by HeroicKatora** [comment]
@jramapuram Mostly the simplistic ones. 

`jpeg` is likely a huge winner as it is block based. If a block is completely unecessary I think you can skip it.

`png` has decreased memory usage but is likely not severly faster as compression and decorrelation will still decode fill scanlines at a time and the more complex prediction filters will necessitate keeping at least the full previous scanline in memory. Other, less compressible filter methods will fare better so that an adaptive algorithm could optimize memory usage in these cases.

`pnm` in binary is just an image matrix so for underlying readers that support `seek` it could gain a good amount of speed and memory. For ascii encoded we gain memory advantage and a bit of speed when we don't fully validate the input.

`gif` very similar to a binary matrix albeit with slightly awkward 9bit units.

`tiff` is in the simplest format similar to png as pixels are encoded from strips of the pixel matrix. However several more complex extensions exist, including compression, block based methods and tree structures. I'm not sure here but a memory advantage is likely in at least some cases.

`dxt` seems to use 4x4 blocks but the details are unknown to me. Likely could be implemented with a memory advantage.

`bmp` is also a pixel raster.

So many of these can gain an improved performance when reading in terms of memory consumption but keep in mind that those are merely the most simplistic formats. Maybe the best option would be a separate trait as it is a generalizable feature but keeping it in the main trait could slow down the integration of more modern formats with better compression. I'd prefer to stay future proof, especially in a language as young as Rust.

**Comment by jramapuram** [comment]
@HeroicKatora : thanks for the super detailed post! I'll try to convert my existing images to `jpeg` or `pnm` then. Looking through the code though, I see that `JPEGDecoder` and `PNMDecoder` don't implement `read_scanline` ?

```rust
impl<R: Read> ImageDecoder for JPEGDecoder<R> {
...
    fn read_scanline(&mut self, _buf: &mut [u8]) -> ImageResult<u32> {
        unimplemented!();
    }
}
```
It also looks like all the `load_rect` calls use `read_scanline` ? Is this incorrect?

```rust
        loop {
            let row = try!(self.read_scanline(&mut tmp));

            if row - 1 == y {
                break
            }
        }
```

**Comment by HeroicKatora** [comment]
@jramapuram Yes, since the generic interface can't make use of the individual advantages it just calls `read_scanline`. And also the decoders have not focussed on implementing the method. A reinovated interface here could definitely improve the situation, from both implementation and usability perspective.

**Comment by fintelia** [comment]
The `read_scanline` method has been removed in #819.
