### ISSUE TITLE
Panic in JPEG encoder

### ISSUE THREAD

**Issue by Varentsov** [PistonDevelopers/image#431]
I have this error when trying to save the picture as JPEG, with PNG all goes normal.
>thread 'main' panicked at 'shift operation overflowed', /home/nikon/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.3.11/./src/jpeg/encoder.rs:267
An unknown error occurred

maby I doing somthing wrong, here my code:
[http://pastebin.com/RNDWvUPg](http://pastebin.com/RNDWvUPg)

**Comment by Varentsov** [comment]
OK, I found the first issue https://github.com/PistonDevelopers/image/issues/209.
It can be compiled with --release option

**Comment by ruud-v-a** [comment]
This is in fact a bug. Compiling in release mode disables the overflow check, but the overflow should not be there in the first place, or if overflow is the correct behaviour then it should be made explicit.

**Comment by twoodford** [comment]
This overflow occurs when `write_bits()` is called with a size of zero and `self.accumulator` is empty (so that `self.nbits` is zero).  This means that the `u32` is shifted left by 32 bits, which appears to be the cause of the panic.  Checking for a length of zero before attempting to add the bits to the accumulator appears to resolve the problem.
