### ISSUE TITLE
Unexpected output from decoding some ICO files

### ISSUE THREAD

**Issue by mbrubeck** [PistonDevelopers/image#534]
Originally reported as servo/servo#10305: the attached ICO files are not decoded as expected.

[icons.zip](https://github.com/PistonDevelopers/image/files/280745/icons.zip)

**Comment by pix64** [comment]
I'm using a hacked up version of Image because I can't get the PNG encoder to compile (miniz-sys doesn't want to compile out of the box on Windows).

These files report an extremely large value for image length in the image directory header and the image offset doesn't seem to point to the beginning of the image data.

Offsetting smile.ico by an additional 64 bytes before reading image data results in correctly decoding the image.
Offsetting the other two files by an additional 1024 bytes before reading results in correctly decoding the image.

I don't know what the data is at the "beginning" of the image data.

smile.ico (Best Entry)
Img Count: 2
Width: 32
Height: 32
Bits Per Pixel: 0 (Actually 4)
Image Length: 744
Image Offset: 38

icon.ico (1 Entry)
Width: 16
Height: 16
Bits Per Pixel: 0 (Actually 8)
Image Legnth: 1384
Image Offset: 22

win.ico (1 Entry)
Width: 16
Height: 16
Bits Per Pixel: 8
Image Legnth: 1384
Image Offset: 22

**Comment by philipc** [comment]
That extra data is the color palette. We are reading the color palette correctly, but the bug seems to be that read_metadata_in_ico_format() doesn't include the color palette size in data_offset.
