### ISSUE TITLE
image 0.13.0 compile error bug

### ISSUE THREAD

**Issue by lsaether** [PistonDevelopers/image#645]
When I try to compile a crate after importing the image crate, my project panics while trying to build. Returning: 

 Compiling image v0.13.0
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'assertion failed: !unsize', /checkout/src/librustc_typeck/check/mod.rs:2212
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `image`.

**Comment by pix64** [comment]
This is a bug with the rust compiler it's self and not image. I imagine
this bug was recently introduced in the nightly version.

On May 6, 2017 7:00 PM, "lsaether" <notifications@github.com> wrote:

When I try to compile a crate after importing the image crate, my project
panics while trying to build. Returning:

Compiling image v0.13.0
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/
rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'assertion failed: !unsize',
/checkout/src/librustc_typeck/check/mod.rs:2212
note: Run with RUST_BACKTRACE=1 for a backtrace.

error: Could not compile image.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PistonDevelopers/image/issues/645>, or mute the thread

**Comment by HeroicKatora** [comment]
Closing as outdated. Rust `1.18` is no longer supported by `image`.
