### ISSUE TITLE
save() function inconsistency

### ISSUE THREAD

**Issue by mark-summerfield** [PistonDevelopers/image#742]
If you create a new image, you can save it using img.save(filename); but if you open an existing image, doing img.save(filename) doesn't work.
See https://users.rust-lang.org/t/can-create-save-an-image-but-cant-load-modify-save-one/16574

**Comment by calum** [comment]
Your original issue was due to the fact that the first was an `ImageBuffer` and the second was a `DynamicImage`. Both have a `save` function, but both functions are doing something different.

 1. [ImageBuffer save](https://docs.rs/image/0.18.0/image/struct.ImageBuffer.html#method.save) writes to a file path.
 2. [DynamicImage save](https://docs.rs/image/0.18.0/image/enum.DynamicImage.html#method.save) writes to any `Writer`.

To avoid confusion, maybe the first should be `save_to_file`... or maybe they should both be made the same and the first should be generalized to saving to any `Writer`. Maybe the `DynamicImage` save should be less generic and just write to a file path...

I'd be happy to work on this, but I don't know if or what the solution should be.

**Comment by mark-summerfield** [comment]
I hope that they will be made consistent with each other and both work with any Writer (like your 2.), and perhaps also offer convenience save_to_file(filename) methods too.

**Comment by calum** [comment]
I'll work on this then. For now, I'll work to make both `save`s write to a file and create a separate function, `write`, to write to any buffer.
